# Generated by Django 4.2.2 on 2023-06-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_djuser_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('nombre_art', models.CharField(max_length=40)),
                ('fecha_nacimiento', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackid', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='djuser',
            name='ma',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='djuser',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
