# Generated by Django 4.2.2 on 2023-06-30 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_artist_track_djuser_ma_alter_djuser_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='djuser',
            old_name='ma',
            new_name='email',
        ),
    ]
