# Generated by Django 4.2.2 on 2023-06-30 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_rename_ma_djuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='fecha_nacimiento',
            new_name='fecha_lanzamiento',
        ),
    ]
